### ISSUE TITLE
Colour Picker API Issue

### ISSUE THREAD

**Issue by ghost** [bencyna/Catch-Source-Style#7]
Concerned that Colour picker api from either URL or image may be out of our scope and not achievable within the time frame left to deliver MVP of any valid standard given the number of days left.

**Comment by bellasantiago** [comment]
Searched another API that might do the intended function. Check this one out Michelle:
https://cloud.google.com/vision/docs/detecting-properties?apix_params=%7B%22resource%22%3A%7B%7D%7D

**Comment by ghost** [comment]
Issue now resolved with a lot of hardwork
